/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerListMarketsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerListMarketsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerListMarketsResponse
        //private ChannelmanagerListMarketsResponse instance;

        public ChannelmanagerListMarketsResponseTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerListMarketsResponse
            //instance = new ChannelmanagerListMarketsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerListMarketsResponse
        /// </summary>
        [Fact]
        public void ChannelmanagerListMarketsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerListMarketsResponse
            //Assert.IsType<ChannelmanagerListMarketsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Markets'
        /// </summary>
        [Fact]
        public void MarketsTest()
        {
            // TODO unit test for the property 'Markets'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
