/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerChannelStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerChannelStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerChannelStatus
        //private ChannelmanagerChannelStatus instance;

        public ChannelmanagerChannelStatusTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerChannelStatus
            //instance = new ChannelmanagerChannelStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerChannelStatus
        /// </summary>
        [Fact]
        public void ChannelmanagerChannelStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerChannelStatus
            //Assert.IsType<ChannelmanagerChannelStatus>(instance);
        }
    }
}
