/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerCreateChannelRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerCreateChannelRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerCreateChannelRequest
        //private ChannelmanagerCreateChannelRequest instance;

        public ChannelmanagerCreateChannelRequestTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerCreateChannelRequest
            //instance = new ChannelmanagerCreateChannelRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerCreateChannelRequest
        /// </summary>
        [Fact]
        public void ChannelmanagerCreateChannelRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerCreateChannelRequest
            //Assert.IsType<ChannelmanagerCreateChannelRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DefaultLanguage'
        /// </summary>
        [Fact]
        public void DefaultLanguageTest()
        {
            // TODO unit test for the property 'DefaultLanguage'
        }

        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }

        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
