/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerChannelSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerChannelSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerChannelSettings
        //private ChannelmanagerChannelSettings instance;

        public ChannelmanagerChannelSettingsTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerChannelSettings
            //instance = new ChannelmanagerChannelSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerChannelSettings
        /// </summary>
        [Fact]
        public void ChannelmanagerChannelSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerChannelSettings
            //Assert.IsType<ChannelmanagerChannelSettings>(instance);
        }

        /// <summary>
        /// Test the property 'HideOosProducts'
        /// </summary>
        [Fact]
        public void HideOosProductsTest()
        {
            // TODO unit test for the property 'HideOosProducts'
        }

        /// <summary>
        /// Test the property 'HidePricelessProducts'
        /// </summary>
        [Fact]
        public void HidePricelessProductsTest()
        {
            // TODO unit test for the property 'HidePricelessProducts'
        }
    }
}
