/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerListChannelsWithAssociationsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerListChannelsWithAssociationsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerListChannelsWithAssociationsResponse
        //private ChannelmanagerListChannelsWithAssociationsResponse instance;

        public ChannelmanagerListChannelsWithAssociationsResponseTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerListChannelsWithAssociationsResponse
            //instance = new ChannelmanagerListChannelsWithAssociationsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerListChannelsWithAssociationsResponse
        /// </summary>
        [Fact]
        public void ChannelmanagerListChannelsWithAssociationsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerListChannelsWithAssociationsResponse
            //Assert.IsType<ChannelmanagerListChannelsWithAssociationsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
