/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerUpdateMarketRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerUpdateMarketRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerUpdateMarketRequestPayload
        //private ChannelmanagerUpdateMarketRequestPayload instance;

        public ChannelmanagerUpdateMarketRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerUpdateMarketRequestPayload
            //instance = new ChannelmanagerUpdateMarketRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerUpdateMarketRequestPayload
        /// </summary>
        [Fact]
        public void ChannelmanagerUpdateMarketRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerUpdateMarketRequestPayload
            //Assert.IsType<ChannelmanagerUpdateMarketRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Countries'
        /// </summary>
        [Fact]
        public void CountriesTest()
        {
            // TODO unit test for the property 'Countries'
        }
    }
}
