/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerUpdateChannelRequestPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerUpdateChannelRequestPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerUpdateChannelRequestPayload
        //private ChannelmanagerUpdateChannelRequestPayload instance;

        public ChannelmanagerUpdateChannelRequestPayloadTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerUpdateChannelRequestPayload
            //instance = new ChannelmanagerUpdateChannelRequestPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerUpdateChannelRequestPayload
        /// </summary>
        [Fact]
        public void ChannelmanagerUpdateChannelRequestPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerUpdateChannelRequestPayload
            //Assert.IsType<ChannelmanagerUpdateChannelRequestPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DefaultLanguage'
        /// </summary>
        [Fact]
        public void DefaultLanguageTest()
        {
            // TODO unit test for the property 'DefaultLanguage'
        }

        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }

        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
