/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerChannelResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerChannelResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerChannelResponse
        //private ChannelmanagerChannelResponse instance;

        public ChannelmanagerChannelResponseTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerChannelResponse
            //instance = new ChannelmanagerChannelResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerChannelResponse
        /// </summary>
        [Fact]
        public void ChannelmanagerChannelResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerChannelResponse
            //Assert.IsType<ChannelmanagerChannelResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DefaultLanguage'
        /// </summary>
        [Fact]
        public void DefaultLanguageTest()
        {
            // TODO unit test for the property 'DefaultLanguage'
        }

        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }

        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
