/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerAssociationResponseAssociation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerAssociationResponseAssociationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerAssociationResponseAssociation
        //private ChannelmanagerAssociationResponseAssociation instance;

        public ChannelmanagerAssociationResponseAssociationTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerAssociationResponseAssociation
            //instance = new ChannelmanagerAssociationResponseAssociation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerAssociationResponseAssociation
        /// </summary>
        [Fact]
        public void ChannelmanagerAssociationResponseAssociationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerAssociationResponseAssociation
            //Assert.IsType<ChannelmanagerAssociationResponseAssociation>(instance);
        }

        /// <summary>
        /// Test the property 'ChannelGrn'
        /// </summary>
        [Fact]
        public void ChannelGrnTest()
        {
            // TODO unit test for the property 'ChannelGrn'
        }

        /// <summary>
        /// Test the property 'MarketGrn'
        /// </summary>
        [Fact]
        public void MarketGrnTest()
        {
            // TODO unit test for the property 'MarketGrn'
        }
    }
}
