/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerMarketResponseWithAssociationsAssociation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerMarketResponseWithAssociationsAssociationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerMarketResponseWithAssociationsAssociation
        //private ChannelmanagerMarketResponseWithAssociationsAssociation instance;

        public ChannelmanagerMarketResponseWithAssociationsAssociationTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerMarketResponseWithAssociationsAssociation
            //instance = new ChannelmanagerMarketResponseWithAssociationsAssociation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerMarketResponseWithAssociationsAssociation
        /// </summary>
        [Fact]
        public void ChannelmanagerMarketResponseWithAssociationsAssociationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerMarketResponseWithAssociationsAssociation
            //Assert.IsType<ChannelmanagerMarketResponseWithAssociationsAssociation>(instance);
        }

        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }
    }
}
