/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerDeleteMarketRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerDeleteMarketRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerDeleteMarketRequest
        //private ChannelmanagerDeleteMarketRequest instance;

        public ChannelmanagerDeleteMarketRequestTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerDeleteMarketRequest
            //instance = new ChannelmanagerDeleteMarketRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerDeleteMarketRequest
        /// </summary>
        [Fact]
        public void ChannelmanagerDeleteMarketRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerDeleteMarketRequest
            //Assert.IsType<ChannelmanagerDeleteMarketRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
