/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerListChannelsWithAssociationsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerListChannelsWithAssociationsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerListChannelsWithAssociationsRequest
        //private ChannelmanagerListChannelsWithAssociationsRequest instance;

        public ChannelmanagerListChannelsWithAssociationsRequestTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerListChannelsWithAssociationsRequest
            //instance = new ChannelmanagerListChannelsWithAssociationsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerListChannelsWithAssociationsRequest
        /// </summary>
        [Fact]
        public void ChannelmanagerListChannelsWithAssociationsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerListChannelsWithAssociationsRequest
            //Assert.IsType<ChannelmanagerListChannelsWithAssociationsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'PageToken'
        /// </summary>
        [Fact]
        public void PageTokenTest()
        {
            // TODO unit test for the property 'PageToken'
        }
    }
}
