/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerListChannelsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerListChannelsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerListChannelsResponse
        //private ChannelmanagerListChannelsResponse instance;

        public ChannelmanagerListChannelsResponseTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerListChannelsResponse
            //instance = new ChannelmanagerListChannelsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerListChannelsResponse
        /// </summary>
        [Fact]
        public void ChannelmanagerListChannelsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerListChannelsResponse
            //Assert.IsType<ChannelmanagerListChannelsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }

        /// <summary>
        /// Test the property 'NextPageToken'
        /// </summary>
        [Fact]
        public void NextPageTokenTest()
        {
            // TODO unit test for the property 'NextPageToken'
        }
    }
}
