/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerChannelTypeWebsite
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerChannelTypeWebsiteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerChannelTypeWebsite
        //private ChannelmanagerChannelTypeWebsite instance;

        public ChannelmanagerChannelTypeWebsiteTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerChannelTypeWebsite
            //instance = new ChannelmanagerChannelTypeWebsite();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerChannelTypeWebsite
        /// </summary>
        [Fact]
        public void ChannelmanagerChannelTypeWebsiteInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerChannelTypeWebsite
            //Assert.IsType<ChannelmanagerChannelTypeWebsite>(instance);
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
    }
}
