/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using channelmanager.Model;
using channelmanager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace channelmanager.Test.Model
{
    /// <summary>
    ///  Class for testing ChannelmanagerAssociationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelmanagerAssociationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelmanagerAssociationResponse
        //private ChannelmanagerAssociationResponse instance;

        public ChannelmanagerAssociationResponseTests()
        {
            // TODO uncomment below to create an instance of ChannelmanagerAssociationResponse
            //instance = new ChannelmanagerAssociationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelmanagerAssociationResponse
        /// </summary>
        [Fact]
        public void ChannelmanagerAssociationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChannelmanagerAssociationResponse
            //Assert.IsType<ChannelmanagerAssociationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Grn'
        /// </summary>
        [Fact]
        public void GrnTest()
        {
            // TODO unit test for the property 'Grn'
        }

        /// <summary>
        /// Test the property 'AssociationEntities'
        /// </summary>
        [Fact]
        public void AssociationEntitiesTest()
        {
            // TODO unit test for the property 'AssociationEntities'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
