/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using channelmanager.Client;
using channelmanager.Api;
// uncomment below to import models
//using channelmanager.Model;

namespace channelmanager.Test.Api
{
    /// <summary>
    ///  Class for testing ChannelManagerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ChannelManagerApiTests : IDisposable
    {
        private ChannelManagerApi instance;

        public ChannelManagerApiTests()
        {
            instance = new ChannelManagerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelManagerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ChannelManagerApi
            //Assert.IsType<ChannelManagerApi>(instance);
        }

        /// <summary>
        /// Test ChannelManagerCreateAssociation
        /// </summary>
        [Fact]
        public void ChannelManagerCreateAssociationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerCreateAssociationRequest body = null;
            //var response = instance.ChannelManagerCreateAssociation(body);
            //Assert.IsType<ChannelmanagerAssociationResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerCreateChannel
        /// </summary>
        [Fact]
        public void ChannelManagerCreateChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerCreateChannelRequest body = null;
            //var response = instance.ChannelManagerCreateChannel(body);
            //Assert.IsType<ChannelmanagerChannelResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerCreateMarket
        /// </summary>
        [Fact]
        public void ChannelManagerCreateMarketTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerCreateMarketRequest body = null;
            //var response = instance.ChannelManagerCreateMarket(body);
            //Assert.IsType<ChannelmanagerMarketResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerDeleteAssociation
        /// </summary>
        [Fact]
        public void ChannelManagerDeleteAssociationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerDeleteAssociationRequest body = null;
            //var response = instance.ChannelManagerDeleteAssociation(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ChannelManagerDeleteChannel
        /// </summary>
        [Fact]
        public void ChannelManagerDeleteChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerDeleteChannelRequest body = null;
            //var response = instance.ChannelManagerDeleteChannel(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ChannelManagerDeleteMarket
        /// </summary>
        [Fact]
        public void ChannelManagerDeleteMarketTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerDeleteMarketRequest body = null;
            //var response = instance.ChannelManagerDeleteMarket(body);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test ChannelManagerGetChannel
        /// </summary>
        [Fact]
        public void ChannelManagerGetChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerGetChannelRequest body = null;
            //var response = instance.ChannelManagerGetChannel(body);
            //Assert.IsType<ChannelmanagerChannelResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerGetChannelWithAssociations
        /// </summary>
        [Fact]
        public void ChannelManagerGetChannelWithAssociationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerGetChannelWithAssociationsRequest body = null;
            //var response = instance.ChannelManagerGetChannelWithAssociations(body);
            //Assert.IsType<ChannelmanagerChannelResponseWithAssociations>(response);
        }

        /// <summary>
        /// Test ChannelManagerGetMarket
        /// </summary>
        [Fact]
        public void ChannelManagerGetMarketTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerGetMarketRequest body = null;
            //var response = instance.ChannelManagerGetMarket(body);
            //Assert.IsType<ChannelmanagerMarketResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerGetMarketWithAssociations
        /// </summary>
        [Fact]
        public void ChannelManagerGetMarketWithAssociationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerGetMarketWithAssociationsRequest body = null;
            //var response = instance.ChannelManagerGetMarketWithAssociations(body);
            //Assert.IsType<ChannelmanagerMarketResponseWithAssociations>(response);
        }

        /// <summary>
        /// Test ChannelManagerListChannels
        /// </summary>
        [Fact]
        public void ChannelManagerListChannelsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerListChannelsRequest body = null;
            //var response = instance.ChannelManagerListChannels(body);
            //Assert.IsType<ChannelmanagerListChannelsResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerListChannelsWithAssociations
        /// </summary>
        [Fact]
        public void ChannelManagerListChannelsWithAssociationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerListChannelsWithAssociationsRequest body = null;
            //var response = instance.ChannelManagerListChannelsWithAssociations(body);
            //Assert.IsType<ChannelmanagerListChannelsWithAssociationsResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerListMarkets
        /// </summary>
        [Fact]
        public void ChannelManagerListMarketsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerListMarketsRequest body = null;
            //var response = instance.ChannelManagerListMarkets(body);
            //Assert.IsType<ChannelmanagerListMarketsResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerListMarketsWithAssociations
        /// </summary>
        [Fact]
        public void ChannelManagerListMarketsWithAssociationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerListMarketsWithAssociationsRequest body = null;
            //var response = instance.ChannelManagerListMarketsWithAssociations(body);
            //Assert.IsType<ChannelmanagerListMarketsWithAssociationsResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerUpdateChannel
        /// </summary>
        [Fact]
        public void ChannelManagerUpdateChannelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerUpdateChannelRequest body = null;
            //var response = instance.ChannelManagerUpdateChannel(body);
            //Assert.IsType<ChannelmanagerChannelResponse>(response);
        }

        /// <summary>
        /// Test ChannelManagerUpdateMarket
        /// </summary>
        [Fact]
        public void ChannelManagerUpdateMarketTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChannelmanagerUpdateMarketRequest body = null;
            //var response = instance.ChannelManagerUpdateMarket(body);
            //Assert.IsType<ChannelmanagerMarketResponse>(response);
        }
    }
}
