/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = channelmanager.Client.OpenAPIDateConverter;

namespace channelmanager.Model
{
    /// <summary>
    /// Defines channelmanagerCountryCode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ChannelmanagerCountryCode
    {
        /// <summary>
        /// Enum UNKNOWN for value: COUNTRY_CODE_UNKNOWN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_UNKNOWN")]
        UNKNOWN = 1,

        /// <summary>
        /// Enum AD for value: COUNTRY_CODE_AD
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AD")]
        AD = 2,

        /// <summary>
        /// Enum AE for value: COUNTRY_CODE_AE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AE")]
        AE = 3,

        /// <summary>
        /// Enum AF for value: COUNTRY_CODE_AF
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AF")]
        AF = 4,

        /// <summary>
        /// Enum AG for value: COUNTRY_CODE_AG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AG")]
        AG = 5,

        /// <summary>
        /// Enum AI for value: COUNTRY_CODE_AI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AI")]
        AI = 6,

        /// <summary>
        /// Enum AL for value: COUNTRY_CODE_AL
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AL")]
        AL = 7,

        /// <summary>
        /// Enum AM for value: COUNTRY_CODE_AM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AM")]
        AM = 8,

        /// <summary>
        /// Enum AO for value: COUNTRY_CODE_AO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AO")]
        AO = 9,

        /// <summary>
        /// Enum AQ for value: COUNTRY_CODE_AQ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AQ")]
        AQ = 10,

        /// <summary>
        /// Enum AR for value: COUNTRY_CODE_AR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AR")]
        AR = 11,

        /// <summary>
        /// Enum AS for value: COUNTRY_CODE_AS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AS")]
        AS = 12,

        /// <summary>
        /// Enum AT for value: COUNTRY_CODE_AT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AT")]
        AT = 13,

        /// <summary>
        /// Enum AU for value: COUNTRY_CODE_AU
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AU")]
        AU = 14,

        /// <summary>
        /// Enum AW for value: COUNTRY_CODE_AW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AW")]
        AW = 15,

        /// <summary>
        /// Enum AX for value: COUNTRY_CODE_AX
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AX")]
        AX = 16,

        /// <summary>
        /// Enum AZ for value: COUNTRY_CODE_AZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_AZ")]
        AZ = 17,

        /// <summary>
        /// Enum BA for value: COUNTRY_CODE_BA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BA")]
        BA = 18,

        /// <summary>
        /// Enum BB for value: COUNTRY_CODE_BB
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BB")]
        BB = 19,

        /// <summary>
        /// Enum BD for value: COUNTRY_CODE_BD
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BD")]
        BD = 20,

        /// <summary>
        /// Enum BE for value: COUNTRY_CODE_BE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BE")]
        BE = 21,

        /// <summary>
        /// Enum BF for value: COUNTRY_CODE_BF
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BF")]
        BF = 22,

        /// <summary>
        /// Enum BG for value: COUNTRY_CODE_BG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BG")]
        BG = 23,

        /// <summary>
        /// Enum BH for value: COUNTRY_CODE_BH
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BH")]
        BH = 24,

        /// <summary>
        /// Enum BI for value: COUNTRY_CODE_BI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BI")]
        BI = 25,

        /// <summary>
        /// Enum BJ for value: COUNTRY_CODE_BJ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BJ")]
        BJ = 26,

        /// <summary>
        /// Enum BL for value: COUNTRY_CODE_BL
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BL")]
        BL = 27,

        /// <summary>
        /// Enum BM for value: COUNTRY_CODE_BM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BM")]
        BM = 28,

        /// <summary>
        /// Enum BN for value: COUNTRY_CODE_BN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BN")]
        BN = 29,

        /// <summary>
        /// Enum BO for value: COUNTRY_CODE_BO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BO")]
        BO = 30,

        /// <summary>
        /// Enum BQ for value: COUNTRY_CODE_BQ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BQ")]
        BQ = 31,

        /// <summary>
        /// Enum BR for value: COUNTRY_CODE_BR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BR")]
        BR = 32,

        /// <summary>
        /// Enum BS for value: COUNTRY_CODE_BS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BS")]
        BS = 33,

        /// <summary>
        /// Enum BT for value: COUNTRY_CODE_BT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BT")]
        BT = 34,

        /// <summary>
        /// Enum BV for value: COUNTRY_CODE_BV
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BV")]
        BV = 35,

        /// <summary>
        /// Enum BW for value: COUNTRY_CODE_BW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BW")]
        BW = 36,

        /// <summary>
        /// Enum BY for value: COUNTRY_CODE_BY
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BY")]
        BY = 37,

        /// <summary>
        /// Enum BZ for value: COUNTRY_CODE_BZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_BZ")]
        BZ = 38,

        /// <summary>
        /// Enum CA for value: COUNTRY_CODE_CA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CA")]
        CA = 39,

        /// <summary>
        /// Enum CC for value: COUNTRY_CODE_CC
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CC")]
        CC = 40,

        /// <summary>
        /// Enum CD for value: COUNTRY_CODE_CD
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CD")]
        CD = 41,

        /// <summary>
        /// Enum CF for value: COUNTRY_CODE_CF
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CF")]
        CF = 42,

        /// <summary>
        /// Enum CG for value: COUNTRY_CODE_CG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CG")]
        CG = 43,

        /// <summary>
        /// Enum CH for value: COUNTRY_CODE_CH
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CH")]
        CH = 44,

        /// <summary>
        /// Enum CI for value: COUNTRY_CODE_CI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CI")]
        CI = 45,

        /// <summary>
        /// Enum CK for value: COUNTRY_CODE_CK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CK")]
        CK = 46,

        /// <summary>
        /// Enum CL for value: COUNTRY_CODE_CL
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CL")]
        CL = 47,

        /// <summary>
        /// Enum CM for value: COUNTRY_CODE_CM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CM")]
        CM = 48,

        /// <summary>
        /// Enum CN for value: COUNTRY_CODE_CN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CN")]
        CN = 49,

        /// <summary>
        /// Enum CO for value: COUNTRY_CODE_CO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CO")]
        CO = 50,

        /// <summary>
        /// Enum CR for value: COUNTRY_CODE_CR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CR")]
        CR = 51,

        /// <summary>
        /// Enum CU for value: COUNTRY_CODE_CU
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CU")]
        CU = 52,

        /// <summary>
        /// Enum CV for value: COUNTRY_CODE_CV
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CV")]
        CV = 53,

        /// <summary>
        /// Enum CW for value: COUNTRY_CODE_CW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CW")]
        CW = 54,

        /// <summary>
        /// Enum CX for value: COUNTRY_CODE_CX
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CX")]
        CX = 55,

        /// <summary>
        /// Enum CY for value: COUNTRY_CODE_CY
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CY")]
        CY = 56,

        /// <summary>
        /// Enum CZ for value: COUNTRY_CODE_CZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_CZ")]
        CZ = 57,

        /// <summary>
        /// Enum DE for value: COUNTRY_CODE_DE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_DE")]
        DE = 58,

        /// <summary>
        /// Enum DJ for value: COUNTRY_CODE_DJ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_DJ")]
        DJ = 59,

        /// <summary>
        /// Enum DK for value: COUNTRY_CODE_DK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_DK")]
        DK = 60,

        /// <summary>
        /// Enum DM for value: COUNTRY_CODE_DM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_DM")]
        DM = 61,

        /// <summary>
        /// Enum DO for value: COUNTRY_CODE_DO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_DO")]
        DO = 62,

        /// <summary>
        /// Enum DZ for value: COUNTRY_CODE_DZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_DZ")]
        DZ = 63,

        /// <summary>
        /// Enum EC for value: COUNTRY_CODE_EC
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_EC")]
        EC = 64,

        /// <summary>
        /// Enum EE for value: COUNTRY_CODE_EE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_EE")]
        EE = 65,

        /// <summary>
        /// Enum EG for value: COUNTRY_CODE_EG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_EG")]
        EG = 66,

        /// <summary>
        /// Enum EH for value: COUNTRY_CODE_EH
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_EH")]
        EH = 67,

        /// <summary>
        /// Enum ER for value: COUNTRY_CODE_ER
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ER")]
        ER = 68,

        /// <summary>
        /// Enum ES for value: COUNTRY_CODE_ES
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ES")]
        ES = 69,

        /// <summary>
        /// Enum ET for value: COUNTRY_CODE_ET
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ET")]
        ET = 70,

        /// <summary>
        /// Enum FI for value: COUNTRY_CODE_FI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_FI")]
        FI = 71,

        /// <summary>
        /// Enum FJ for value: COUNTRY_CODE_FJ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_FJ")]
        FJ = 72,

        /// <summary>
        /// Enum FK for value: COUNTRY_CODE_FK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_FK")]
        FK = 73,

        /// <summary>
        /// Enum FM for value: COUNTRY_CODE_FM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_FM")]
        FM = 74,

        /// <summary>
        /// Enum FO for value: COUNTRY_CODE_FO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_FO")]
        FO = 75,

        /// <summary>
        /// Enum FR for value: COUNTRY_CODE_FR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_FR")]
        FR = 76,

        /// <summary>
        /// Enum GA for value: COUNTRY_CODE_GA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GA")]
        GA = 77,

        /// <summary>
        /// Enum GB for value: COUNTRY_CODE_GB
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GB")]
        GB = 78,

        /// <summary>
        /// Enum GD for value: COUNTRY_CODE_GD
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GD")]
        GD = 79,

        /// <summary>
        /// Enum GE for value: COUNTRY_CODE_GE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GE")]
        GE = 80,

        /// <summary>
        /// Enum GF for value: COUNTRY_CODE_GF
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GF")]
        GF = 81,

        /// <summary>
        /// Enum GG for value: COUNTRY_CODE_GG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GG")]
        GG = 82,

        /// <summary>
        /// Enum GH for value: COUNTRY_CODE_GH
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GH")]
        GH = 83,

        /// <summary>
        /// Enum GI for value: COUNTRY_CODE_GI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GI")]
        GI = 84,

        /// <summary>
        /// Enum GL for value: COUNTRY_CODE_GL
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GL")]
        GL = 85,

        /// <summary>
        /// Enum GM for value: COUNTRY_CODE_GM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GM")]
        GM = 86,

        /// <summary>
        /// Enum GN for value: COUNTRY_CODE_GN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GN")]
        GN = 87,

        /// <summary>
        /// Enum GP for value: COUNTRY_CODE_GP
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GP")]
        GP = 88,

        /// <summary>
        /// Enum GQ for value: COUNTRY_CODE_GQ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GQ")]
        GQ = 89,

        /// <summary>
        /// Enum GR for value: COUNTRY_CODE_GR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GR")]
        GR = 90,

        /// <summary>
        /// Enum GS for value: COUNTRY_CODE_GS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GS")]
        GS = 91,

        /// <summary>
        /// Enum GT for value: COUNTRY_CODE_GT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GT")]
        GT = 92,

        /// <summary>
        /// Enum GU for value: COUNTRY_CODE_GU
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GU")]
        GU = 93,

        /// <summary>
        /// Enum GW for value: COUNTRY_CODE_GW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GW")]
        GW = 94,

        /// <summary>
        /// Enum GY for value: COUNTRY_CODE_GY
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_GY")]
        GY = 95,

        /// <summary>
        /// Enum HK for value: COUNTRY_CODE_HK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_HK")]
        HK = 96,

        /// <summary>
        /// Enum HM for value: COUNTRY_CODE_HM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_HM")]
        HM = 97,

        /// <summary>
        /// Enum HN for value: COUNTRY_CODE_HN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_HN")]
        HN = 98,

        /// <summary>
        /// Enum HR for value: COUNTRY_CODE_HR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_HR")]
        HR = 99,

        /// <summary>
        /// Enum HT for value: COUNTRY_CODE_HT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_HT")]
        HT = 100,

        /// <summary>
        /// Enum HU for value: COUNTRY_CODE_HU
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_HU")]
        HU = 101,

        /// <summary>
        /// Enum ID for value: COUNTRY_CODE_ID
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ID")]
        ID = 102,

        /// <summary>
        /// Enum IE for value: COUNTRY_CODE_IE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_IE")]
        IE = 103,

        /// <summary>
        /// Enum IL for value: COUNTRY_CODE_IL
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_IL")]
        IL = 104,

        /// <summary>
        /// Enum IM for value: COUNTRY_CODE_IM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_IM")]
        IM = 105,

        /// <summary>
        /// Enum IN for value: COUNTRY_CODE_IN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_IN")]
        IN = 106,

        /// <summary>
        /// Enum IO for value: COUNTRY_CODE_IO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_IO")]
        IO = 107,

        /// <summary>
        /// Enum IQ for value: COUNTRY_CODE_IQ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_IQ")]
        IQ = 108,

        /// <summary>
        /// Enum IR for value: COUNTRY_CODE_IR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_IR")]
        IR = 109,

        /// <summary>
        /// Enum IS for value: COUNTRY_CODE_IS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_IS")]
        IS = 110,

        /// <summary>
        /// Enum IT for value: COUNTRY_CODE_IT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_IT")]
        IT = 111,

        /// <summary>
        /// Enum JE for value: COUNTRY_CODE_JE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_JE")]
        JE = 112,

        /// <summary>
        /// Enum JM for value: COUNTRY_CODE_JM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_JM")]
        JM = 113,

        /// <summary>
        /// Enum JO for value: COUNTRY_CODE_JO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_JO")]
        JO = 114,

        /// <summary>
        /// Enum JP for value: COUNTRY_CODE_JP
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_JP")]
        JP = 115,

        /// <summary>
        /// Enum KE for value: COUNTRY_CODE_KE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KE")]
        KE = 116,

        /// <summary>
        /// Enum KG for value: COUNTRY_CODE_KG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KG")]
        KG = 117,

        /// <summary>
        /// Enum KH for value: COUNTRY_CODE_KH
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KH")]
        KH = 118,

        /// <summary>
        /// Enum KI for value: COUNTRY_CODE_KI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KI")]
        KI = 119,

        /// <summary>
        /// Enum KM for value: COUNTRY_CODE_KM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KM")]
        KM = 120,

        /// <summary>
        /// Enum KN for value: COUNTRY_CODE_KN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KN")]
        KN = 121,

        /// <summary>
        /// Enum KP for value: COUNTRY_CODE_KP
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KP")]
        KP = 122,

        /// <summary>
        /// Enum KR for value: COUNTRY_CODE_KR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KR")]
        KR = 123,

        /// <summary>
        /// Enum KW for value: COUNTRY_CODE_KW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KW")]
        KW = 124,

        /// <summary>
        /// Enum KY for value: COUNTRY_CODE_KY
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KY")]
        KY = 125,

        /// <summary>
        /// Enum KZ for value: COUNTRY_CODE_KZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_KZ")]
        KZ = 126,

        /// <summary>
        /// Enum LA for value: COUNTRY_CODE_LA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LA")]
        LA = 127,

        /// <summary>
        /// Enum LB for value: COUNTRY_CODE_LB
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LB")]
        LB = 128,

        /// <summary>
        /// Enum LC for value: COUNTRY_CODE_LC
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LC")]
        LC = 129,

        /// <summary>
        /// Enum LI for value: COUNTRY_CODE_LI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LI")]
        LI = 130,

        /// <summary>
        /// Enum LK for value: COUNTRY_CODE_LK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LK")]
        LK = 131,

        /// <summary>
        /// Enum LR for value: COUNTRY_CODE_LR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LR")]
        LR = 132,

        /// <summary>
        /// Enum LS for value: COUNTRY_CODE_LS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LS")]
        LS = 133,

        /// <summary>
        /// Enum LT for value: COUNTRY_CODE_LT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LT")]
        LT = 134,

        /// <summary>
        /// Enum LU for value: COUNTRY_CODE_LU
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LU")]
        LU = 135,

        /// <summary>
        /// Enum LV for value: COUNTRY_CODE_LV
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LV")]
        LV = 136,

        /// <summary>
        /// Enum LY for value: COUNTRY_CODE_LY
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_LY")]
        LY = 137,

        /// <summary>
        /// Enum MA for value: COUNTRY_CODE_MA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MA")]
        MA = 138,

        /// <summary>
        /// Enum MC for value: COUNTRY_CODE_MC
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MC")]
        MC = 139,

        /// <summary>
        /// Enum MD for value: COUNTRY_CODE_MD
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MD")]
        MD = 140,

        /// <summary>
        /// Enum ME for value: COUNTRY_CODE_ME
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ME")]
        ME = 141,

        /// <summary>
        /// Enum MF for value: COUNTRY_CODE_MF
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MF")]
        MF = 142,

        /// <summary>
        /// Enum MG for value: COUNTRY_CODE_MG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MG")]
        MG = 143,

        /// <summary>
        /// Enum MH for value: COUNTRY_CODE_MH
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MH")]
        MH = 144,

        /// <summary>
        /// Enum MK for value: COUNTRY_CODE_MK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MK")]
        MK = 145,

        /// <summary>
        /// Enum ML for value: COUNTRY_CODE_ML
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ML")]
        ML = 146,

        /// <summary>
        /// Enum MM for value: COUNTRY_CODE_MM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MM")]
        MM = 147,

        /// <summary>
        /// Enum MN for value: COUNTRY_CODE_MN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MN")]
        MN = 148,

        /// <summary>
        /// Enum MO for value: COUNTRY_CODE_MO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MO")]
        MO = 149,

        /// <summary>
        /// Enum MP for value: COUNTRY_CODE_MP
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MP")]
        MP = 150,

        /// <summary>
        /// Enum MQ for value: COUNTRY_CODE_MQ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MQ")]
        MQ = 151,

        /// <summary>
        /// Enum MR for value: COUNTRY_CODE_MR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MR")]
        MR = 152,

        /// <summary>
        /// Enum MS for value: COUNTRY_CODE_MS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MS")]
        MS = 153,

        /// <summary>
        /// Enum MT for value: COUNTRY_CODE_MT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MT")]
        MT = 154,

        /// <summary>
        /// Enum MU for value: COUNTRY_CODE_MU
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MU")]
        MU = 155,

        /// <summary>
        /// Enum MV for value: COUNTRY_CODE_MV
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MV")]
        MV = 156,

        /// <summary>
        /// Enum MW for value: COUNTRY_CODE_MW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MW")]
        MW = 157,

        /// <summary>
        /// Enum MX for value: COUNTRY_CODE_MX
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MX")]
        MX = 158,

        /// <summary>
        /// Enum MY for value: COUNTRY_CODE_MY
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MY")]
        MY = 159,

        /// <summary>
        /// Enum MZ for value: COUNTRY_CODE_MZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_MZ")]
        MZ = 160,

        /// <summary>
        /// Enum NA for value: COUNTRY_CODE_NA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NA")]
        NA = 161,

        /// <summary>
        /// Enum NC for value: COUNTRY_CODE_NC
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NC")]
        NC = 162,

        /// <summary>
        /// Enum NE for value: COUNTRY_CODE_NE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NE")]
        NE = 163,

        /// <summary>
        /// Enum NF for value: COUNTRY_CODE_NF
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NF")]
        NF = 164,

        /// <summary>
        /// Enum NG for value: COUNTRY_CODE_NG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NG")]
        NG = 165,

        /// <summary>
        /// Enum NI for value: COUNTRY_CODE_NI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NI")]
        NI = 166,

        /// <summary>
        /// Enum NL for value: COUNTRY_CODE_NL
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NL")]
        NL = 167,

        /// <summary>
        /// Enum NO for value: COUNTRY_CODE_NO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NO")]
        NO = 168,

        /// <summary>
        /// Enum NP for value: COUNTRY_CODE_NP
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NP")]
        NP = 169,

        /// <summary>
        /// Enum NR for value: COUNTRY_CODE_NR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NR")]
        NR = 170,

        /// <summary>
        /// Enum NU for value: COUNTRY_CODE_NU
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NU")]
        NU = 171,

        /// <summary>
        /// Enum NZ for value: COUNTRY_CODE_NZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_NZ")]
        NZ = 172,

        /// <summary>
        /// Enum OM for value: COUNTRY_CODE_OM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_OM")]
        OM = 173,

        /// <summary>
        /// Enum PA for value: COUNTRY_CODE_PA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PA")]
        PA = 174,

        /// <summary>
        /// Enum PE for value: COUNTRY_CODE_PE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PE")]
        PE = 175,

        /// <summary>
        /// Enum PF for value: COUNTRY_CODE_PF
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PF")]
        PF = 176,

        /// <summary>
        /// Enum PG for value: COUNTRY_CODE_PG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PG")]
        PG = 177,

        /// <summary>
        /// Enum PH for value: COUNTRY_CODE_PH
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PH")]
        PH = 178,

        /// <summary>
        /// Enum PK for value: COUNTRY_CODE_PK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PK")]
        PK = 179,

        /// <summary>
        /// Enum PL for value: COUNTRY_CODE_PL
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PL")]
        PL = 180,

        /// <summary>
        /// Enum PM for value: COUNTRY_CODE_PM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PM")]
        PM = 181,

        /// <summary>
        /// Enum PN for value: COUNTRY_CODE_PN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PN")]
        PN = 182,

        /// <summary>
        /// Enum PR for value: COUNTRY_CODE_PR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PR")]
        PR = 183,

        /// <summary>
        /// Enum PS for value: COUNTRY_CODE_PS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PS")]
        PS = 184,

        /// <summary>
        /// Enum PT for value: COUNTRY_CODE_PT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PT")]
        PT = 185,

        /// <summary>
        /// Enum PW for value: COUNTRY_CODE_PW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PW")]
        PW = 186,

        /// <summary>
        /// Enum PY for value: COUNTRY_CODE_PY
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_PY")]
        PY = 187,

        /// <summary>
        /// Enum QA for value: COUNTRY_CODE_QA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_QA")]
        QA = 188,

        /// <summary>
        /// Enum RE for value: COUNTRY_CODE_RE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_RE")]
        RE = 189,

        /// <summary>
        /// Enum RO for value: COUNTRY_CODE_RO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_RO")]
        RO = 190,

        /// <summary>
        /// Enum RS for value: COUNTRY_CODE_RS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_RS")]
        RS = 191,

        /// <summary>
        /// Enum RU for value: COUNTRY_CODE_RU
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_RU")]
        RU = 192,

        /// <summary>
        /// Enum RW for value: COUNTRY_CODE_RW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_RW")]
        RW = 193,

        /// <summary>
        /// Enum SA for value: COUNTRY_CODE_SA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SA")]
        SA = 194,

        /// <summary>
        /// Enum SB for value: COUNTRY_CODE_SB
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SB")]
        SB = 195,

        /// <summary>
        /// Enum SC for value: COUNTRY_CODE_SC
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SC")]
        SC = 196,

        /// <summary>
        /// Enum SD for value: COUNTRY_CODE_SD
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SD")]
        SD = 197,

        /// <summary>
        /// Enum SE for value: COUNTRY_CODE_SE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SE")]
        SE = 198,

        /// <summary>
        /// Enum SG for value: COUNTRY_CODE_SG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SG")]
        SG = 199,

        /// <summary>
        /// Enum SH for value: COUNTRY_CODE_SH
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SH")]
        SH = 200,

        /// <summary>
        /// Enum SI for value: COUNTRY_CODE_SI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SI")]
        SI = 201,

        /// <summary>
        /// Enum SJ for value: COUNTRY_CODE_SJ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SJ")]
        SJ = 202,

        /// <summary>
        /// Enum SK for value: COUNTRY_CODE_SK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SK")]
        SK = 203,

        /// <summary>
        /// Enum SL for value: COUNTRY_CODE_SL
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SL")]
        SL = 204,

        /// <summary>
        /// Enum SM for value: COUNTRY_CODE_SM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SM")]
        SM = 205,

        /// <summary>
        /// Enum SN for value: COUNTRY_CODE_SN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SN")]
        SN = 206,

        /// <summary>
        /// Enum SO for value: COUNTRY_CODE_SO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SO")]
        SO = 207,

        /// <summary>
        /// Enum SR for value: COUNTRY_CODE_SR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SR")]
        SR = 208,

        /// <summary>
        /// Enum SS for value: COUNTRY_CODE_SS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SS")]
        SS = 209,

        /// <summary>
        /// Enum ST for value: COUNTRY_CODE_ST
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ST")]
        ST = 210,

        /// <summary>
        /// Enum SV for value: COUNTRY_CODE_SV
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SV")]
        SV = 211,

        /// <summary>
        /// Enum SX for value: COUNTRY_CODE_SX
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SX")]
        SX = 212,

        /// <summary>
        /// Enum SY for value: COUNTRY_CODE_SY
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SY")]
        SY = 213,

        /// <summary>
        /// Enum SZ for value: COUNTRY_CODE_SZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_SZ")]
        SZ = 214,

        /// <summary>
        /// Enum TC for value: COUNTRY_CODE_TC
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TC")]
        TC = 215,

        /// <summary>
        /// Enum TD for value: COUNTRY_CODE_TD
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TD")]
        TD = 216,

        /// <summary>
        /// Enum TF for value: COUNTRY_CODE_TF
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TF")]
        TF = 217,

        /// <summary>
        /// Enum TG for value: COUNTRY_CODE_TG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TG")]
        TG = 218,

        /// <summary>
        /// Enum TH for value: COUNTRY_CODE_TH
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TH")]
        TH = 219,

        /// <summary>
        /// Enum TJ for value: COUNTRY_CODE_TJ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TJ")]
        TJ = 220,

        /// <summary>
        /// Enum TK for value: COUNTRY_CODE_TK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TK")]
        TK = 221,

        /// <summary>
        /// Enum TL for value: COUNTRY_CODE_TL
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TL")]
        TL = 222,

        /// <summary>
        /// Enum TM for value: COUNTRY_CODE_TM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TM")]
        TM = 223,

        /// <summary>
        /// Enum TN for value: COUNTRY_CODE_TN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TN")]
        TN = 224,

        /// <summary>
        /// Enum TO for value: COUNTRY_CODE_TO
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TO")]
        TO = 225,

        /// <summary>
        /// Enum TR for value: COUNTRY_CODE_TR
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TR")]
        TR = 226,

        /// <summary>
        /// Enum TT for value: COUNTRY_CODE_TT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TT")]
        TT = 227,

        /// <summary>
        /// Enum TV for value: COUNTRY_CODE_TV
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TV")]
        TV = 228,

        /// <summary>
        /// Enum TW for value: COUNTRY_CODE_TW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TW")]
        TW = 229,

        /// <summary>
        /// Enum TZ for value: COUNTRY_CODE_TZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_TZ")]
        TZ = 230,

        /// <summary>
        /// Enum UA for value: COUNTRY_CODE_UA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_UA")]
        UA = 231,

        /// <summary>
        /// Enum UG for value: COUNTRY_CODE_UG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_UG")]
        UG = 232,

        /// <summary>
        /// Enum UM for value: COUNTRY_CODE_UM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_UM")]
        UM = 233,

        /// <summary>
        /// Enum US for value: COUNTRY_CODE_US
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_US")]
        US = 234,

        /// <summary>
        /// Enum UY for value: COUNTRY_CODE_UY
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_UY")]
        UY = 235,

        /// <summary>
        /// Enum UZ for value: COUNTRY_CODE_UZ
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_UZ")]
        UZ = 236,

        /// <summary>
        /// Enum VA for value: COUNTRY_CODE_VA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_VA")]
        VA = 237,

        /// <summary>
        /// Enum VC for value: COUNTRY_CODE_VC
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_VC")]
        VC = 238,

        /// <summary>
        /// Enum VE for value: COUNTRY_CODE_VE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_VE")]
        VE = 239,

        /// <summary>
        /// Enum VG for value: COUNTRY_CODE_VG
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_VG")]
        VG = 240,

        /// <summary>
        /// Enum VI for value: COUNTRY_CODE_VI
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_VI")]
        VI = 241,

        /// <summary>
        /// Enum VN for value: COUNTRY_CODE_VN
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_VN")]
        VN = 242,

        /// <summary>
        /// Enum VU for value: COUNTRY_CODE_VU
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_VU")]
        VU = 243,

        /// <summary>
        /// Enum WF for value: COUNTRY_CODE_WF
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_WF")]
        WF = 244,

        /// <summary>
        /// Enum WS for value: COUNTRY_CODE_WS
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_WS")]
        WS = 245,

        /// <summary>
        /// Enum YE for value: COUNTRY_CODE_YE
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_YE")]
        YE = 246,

        /// <summary>
        /// Enum YT for value: COUNTRY_CODE_YT
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_YT")]
        YT = 247,

        /// <summary>
        /// Enum ZA for value: COUNTRY_CODE_ZA
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ZA")]
        ZA = 248,

        /// <summary>
        /// Enum ZM for value: COUNTRY_CODE_ZM
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ZM")]
        ZM = 249,

        /// <summary>
        /// Enum ZW for value: COUNTRY_CODE_ZW
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_ZW")]
        ZW = 250,

        /// <summary>
        /// Enum XK for value: COUNTRY_CODE_XK
        /// </summary>
        [EnumMember(Value = "COUNTRY_CODE_XK")]
        XK = 251
    }

}
