/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = channelmanager.Client.OpenAPIDateConverter;

namespace channelmanager.Model
{
    /// <summary>
    /// Defines channelmanagerChannelStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ChannelmanagerChannelStatus
    {
        /// <summary>
        /// Enum UNKNOWN for value: CH_STATUS_UNKNOWN
        /// </summary>
        [EnumMember(Value = "CH_STATUS_UNKNOWN")]
        UNKNOWN = 1,

        /// <summary>
        /// Enum ACTIVE for value: CH_STATUS_ACTIVE
        /// </summary>
        [EnumMember(Value = "CH_STATUS_ACTIVE")]
        ACTIVE = 2,

        /// <summary>
        /// Enum DISABLED for value: CH_STATUS_DISABLED
        /// </summary>
        [EnumMember(Value = "CH_STATUS_DISABLED")]
        DISABLED = 3,

        /// <summary>
        /// Enum UNDERMAINTENANCE for value: CH_STATUS_UNDER_MAINTENANCE
        /// </summary>
        [EnumMember(Value = "CH_STATUS_UNDER_MAINTENANCE")]
        UNDERMAINTENANCE = 4
    }

}
