/*
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = channelmanager.Client.OpenAPIDateConverter;

namespace channelmanager.Model
{
    /// <summary>
    /// ChannelmanagerCreateAssociationRequest
    /// </summary>
    [DataContract(Name = "channelmanagerCreateAssociationRequest")]
    public partial class ChannelmanagerCreateAssociationRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelmanagerCreateAssociationRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ChannelmanagerCreateAssociationRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelmanagerCreateAssociationRequest" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId (required).</param>
        /// <param name="channelGrn">channelGrn (required).</param>
        /// <param name="marketGrn">marketGrn (required).</param>
        public ChannelmanagerCreateAssociationRequest(string tenantId = default(string), string channelGrn = default(string), string marketGrn = default(string))
        {
            // to ensure "tenantId" is required (not null)
            if (tenantId == null)
            {
                throw new ArgumentNullException("tenantId is a required property for ChannelmanagerCreateAssociationRequest and cannot be null");
            }
            this.TenantId = tenantId;
            // to ensure "channelGrn" is required (not null)
            if (channelGrn == null)
            {
                throw new ArgumentNullException("channelGrn is a required property for ChannelmanagerCreateAssociationRequest and cannot be null");
            }
            this.ChannelGrn = channelGrn;
            // to ensure "marketGrn" is required (not null)
            if (marketGrn == null)
            {
                throw new ArgumentNullException("marketGrn is a required property for ChannelmanagerCreateAssociationRequest and cannot be null");
            }
            this.MarketGrn = marketGrn;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", IsRequired = true, EmitDefaultValue = true)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets ChannelGrn
        /// </summary>
        [DataMember(Name = "channelGrn", IsRequired = true, EmitDefaultValue = true)]
        public string ChannelGrn { get; set; }

        /// <summary>
        /// Gets or Sets MarketGrn
        /// </summary>
        [DataMember(Name = "marketGrn", IsRequired = true, EmitDefaultValue = true)]
        public string MarketGrn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChannelmanagerCreateAssociationRequest {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  ChannelGrn: ").Append(ChannelGrn).Append("\n");
            sb.Append("  MarketGrn: ").Append(MarketGrn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
